apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    name: keycloak

spec:
  ports:
    - port: 9000
      name: management
    - port: 8080
      name: development
    - port: 8443
      name: production
  type: ClusterIP
  selector:
    name: keycloak

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  selector:
    matchLabels:
      name: keycloak
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        name: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:25.0.6
          imagePullPolicy: IfNotPresent
          command:
            - '/opt/keycloak/bin/kc.sh'
            - 'start-dev'
            - '--import-realm'
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
          ports:
            - containerPort: 9000
              name: management
            - containerPort: 8443
              name: production
            - containerPort: 8080
              name: development
          volumeMounts:
            - mountPath: /opt/keycloak/data/import
              name: keycloak-import
      volumes:
        - name: keycloak-import
          configMap:
            name: keycloak

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak
  labels:
    name: keycloak
data:
  realm.json: {{ toJson .Values.keycloak | quote }}
