apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest

spec:
  replicas: 1
  selector:
    matchLabels:
      frontend: postgrest
  template:
    metadata:
      labels:
        frontend: postgrest
    spec:
      initContainers:
        - name: keycloak
          image: alpine/curl
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - "curl --location keycloak:8080/realms/{{ .Values.keycloak.realm }}/protocol/openid-connect/certs > /openid-connect/certs/{{ .Values.keycloak.realm }}.jwks"
          volumeMounts:
            - mountPath: /openid-connect/certs/
              name: openid-connect-certs

      containers:
        - name: postgrest
          image: postgrest/postgrest
          imagePullPolicy: IfNotPresent
          env:
            - name: PGRST_DB_URI
              valueFrom:
                secretKeyRef:
                  key: connection
                  name: authenticate-credentials
            - name: PGRST_DB_ANON_ROLE
              valueFrom:
                secretKeyRef:
                  key: username
                  name: authenticate-credentials
            - name: PGRST_DB_SCHEMAS
              value: {{ .Values.postgrest.api.schema }}
            - name: PGRST_JWT_SECRET
              value: "@/openid-connect/certs/{{ .Values.keycloak.realm }}.jwks"
            - name: PGRST_JWT_ROLE_CLAIM_KEY
              valueFrom:
                secretKeyRef:
                  name: authenticate-credentials
                  key: role-claim-key
          volumeMounts:
            - mountPath: /openid-connect/certs/
              name: openid-connect-certs
      volumes:
        - name: openid-connect-certs
          emptyDir:
            sizeLimit: 1Mi
---

apiVersion: v1
kind: Service
metadata:
  name: postgrest

spec:
  type: NodePort
  selector:
    frontend: postgrest
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: migrations-permissions
data:
  1_permissions.sql: |
    -- +goose Up
    -- +goose StatementBegin
    GRANT USAGE ON SCHEMA {{ .Values.postgrest.api.schema }} TO {{ .Values.postgrest.api.anonymous }};
    GRANT USAGE ON SCHEMA {{ .Values.postgrest.api.schema }} TO {{ .Values.postgrest.api.authorize }};
    CREATE OR REPLACE FUNCTION authz()
        RETURNS TEXT AS $$
    SELECT current_setting('request.jwt.claims', true)::JSON->>'user';
    $$
        LANGUAGE SQL;
    -- +goose StatementEnd

    -- +goose Down
    -- +goose StatementBegin
    REVOKE USAGE ON SCHEMA {{ .Values.postgrest.api.schema }} FROM {{ .Values.postgrest.api.anonymous }};
    REVOKE USAGE ON SCHEMA {{ .Values.postgrest.api.schema }} FROM {{ .Values.postgrest.api.authorize }};
    DROP FUNCTION authz();
    -- +goose StatementEnd
{{- range $index, $table := .Values.postgrest.authorization.tables }}
  {{ add $index 2 }}_{{ $table.schema }}_{{ $table.table }}.sql: |
    {{ include "postgrest.configuration.tables" $table | nindent 4 }}
{{- end }}
