apiVersion: v1
kind: Secret
metadata:
  name: application
data:
  connection: {{ include "database.connection" . | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: migrations
data:
  connection: {{ include "database.migrations" . | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: authentication
data:
  jwt.secret: {{ .Values.application.jwt.secret | b64enc | quote }}
  jwk.public: {{ .Values.application.jwk.public | b64enc | quote }}
