apiVersion: v1
kind: Secret
type: kubebernetes.io/basic-auth
metadata:
  name: "{{ .Values.postgrest.database.username }}-credentials"
  labels:
    cnpg.io/reload: "true"
data:
  username: "{{ .Values.postgrest.database.username | b64enc }}"
  password: "{{ .Values.postgrest.database.password | b64enc }}"
  connection: "{{ include "postgrest.database.connection" . | b64enc }}"
  jwt.secret: "{{ .Values.postgrest.jwk | b64enc }}"

---

apiVersion: v1
kind: Secret
type: kubebernetes.io/basic-auth
metadata:
  name: "goose-credentials"
  labels:
    cnpg.io/reload: "true"
data:
  username: "{{ .Values.goose.username | b64enc }}"
  password: "{{ .Values.goose.password | b64enc }}"
  connection: "{{ include "postgrest.superuser.connection" . | b64enc }}"
