apiVersion: v1
kind: Secret
type: kubebernetes.io/basic-auth
metadata:
  name: pelotech
  labels:
    cnpg.io/reload: "true"
data:
  username: {{ .Values.credentials.pelotech.username | b64enc | quote }}
  password: {{ .Values.credentials.pelotech.password | b64enc | quote }}

---

apiVersion: v1
kind: Secret
type: kubebernetes.io/basic-auth
metadata:
  name: postgrest
  labels:
    cnpg.io/reload: "true"
data:
  username: {{ .Values.credentials.postgrest.username | b64enc | quote }}
  password: {{ .Values.credentials.postgrest.password | b64enc | quote }}
